![](./images/Matrix.svg.png)

### Examples of Common Matrix Operation

In [6]:
A = np.array([np.random.randint(0,10) for i in range(12)]).reshape((3,4))
B = np.array([np.random.randint(0,10) for i in range(12)]).reshape((3,4))

x = np.random.randn(4)
y = np.random.randn(5)

print('A: {}'.format(A))
print('\n')
print('B: {}'.format(B))

print('\n\n')
print('x: {}'.format(x))
print('\n\n')
print('y: {}'.format(y))

A: [[7 8 4 3]
 [4 1 1 6]
 [0 5 2 6]]


B: [[6 6 7 9]
 [5 8 6 3]
 [9 5 5 3]]



x: [-0.62973874  0.48290411 -0.03709649 -0.35250661]



y: [-2.42623614 -1.36089824  1.36234004  0.56839141  0.24492674]


In [7]:
print('A+B:\n', A+B, '\n\n') # matrix addition
print('A-B:\n', A-B, '\n\n') # matrix subtraction
print('A*B:\n', A*B, '\n\n') # ELEMENTWISE multiplication
print('A/B:\n', A/B, '\n\n') # ELEMENTWISE division


print('A*x:\n', A*x, '\n\n') # multiply columns by x
print('A.T:\n', A.T, '\n\n') # transpose (just changes row/column ordering)
print('x.T:\n', x.T, '\n\n') # does nothing (can't transpose 1D array)

A+B:
 [[13 14 11 12]
 [ 9  9  7  9]
 [ 9 10  7  9]] 


A-B:
 [[ 1  2 -3 -6]
 [-1 -7 -5  3]
 [-9  0 -3  3]] 


A*B:
 [[42 48 28 27]
 [20  8  6 18]
 [ 0 25 10 18]] 


A/B:
 [[1.16666667 1.33333333 0.57142857 0.33333333]
 [0.8        0.125      0.16666667 2.        ]
 [0.         1.         0.4        2.        ]] 


A*x:
 [[-4.40817115  3.86323289 -0.14838595 -1.05751982]
 [-2.51895494  0.48290411 -0.03709649 -2.11503964]
 [-0.          2.41452056 -0.07419298 -2.11503964]] 


A.T:
 [[7 4 0]
 [8 1 5]
 [4 1 2]
 [3 6 6]] 


x.T:
 [-0.62973874  0.48290411 -0.03709649 -0.35250661] 




### Systems of Equations
If you recall from your earlier life as a algebra student:

$2x +10 = 18$ has a unique solution; one variable, one equation, one solution

Similarly, two variables with two equations has one solution*   
$x+y=4$  
$2x+2y=10$

However, if we allow 2 variables with only 1 equation, we can have infinite solutions.
$x+y=4$

*(An inconsistent system will have no solution and a system where the second equation is a multiple of the first will have infinite solutions)

### Representing Data as Matrices

1. Write a Matrix to represent this system:   
$x+y=4$  
$2x+2y=10$

2. Multiply your matrix by 3. What is the resulting system of equations? 

3. Solve both your original Matrix and the new Matrix that was the orginal, multiplied by 3.