![](./images/Matrix.svg.png)

### Numpy and Matrices
The numpy package will provide you a great toolbox of optimized mathematical operations including the numpy array, the most convenient way to store vector and matrix data for computation. Here, we'll look at some basic operations in numpy.

In [46]:
A = np.array([np.random.randint(0,10) for i in range(12)]).reshape((3,4))
B = np.array([np.random.randint(0,10) for i in range(12)]).reshape((3,4))

x = np.random.randn(4)
y = np.random.randn(5)

print('A: {}'.format(A))
print('\n')
print('B: {}'.format(B))

print('\n\n')
print('x: {}'.format(x))
print('\n\n')
print('y: {}'.format(y))

A: [[2 8 4 8]
 [6 6 9 5]
 [0 8 2 8]]


B: [[0 6 7 8]
 [8 1 9 4]
 [5 2 4 4]]



x: [-0.35800865 -0.4791102  -0.26180063  0.35003173]



y: [-0.29653411 -0.66575779 -0.46246297  0.2078026   2.11497751]


In [48]:
print('A+B:\n', A+B, '\n\n') # matrix addition
print('A-B:\n', A-B, '\n\n') # matrix subtraction
print('Be careful! This is not standarad matrix multiplication!')
print('A*B:\n', A*B, '\n\n') # ELEMENTWISE multiplication
print('A/B:\n', A/B, '\n\n') # ELEMENTWISE division


print('A*x:\n', A*x, '\n\n') # multiply columns by x
print('A.T:\n', A.T, '\n\n') # transpose (just changes row/column ordering)
print('x.T:\n', x.T, '\n\n') # does nothing (can't transpose 1D array)

A+B:
 [[ 2 14 11 16]
 [14  7 18  9]
 [ 5 10  6 12]] 


A-B:
 [[ 2  2 -3  0]
 [-2  5  0  1]
 [-5  6 -2  4]] 


Be careful! This is not standarad matrix multiplication!
A*B:
 [[ 0 48 28 64]
 [48  6 81 20]
 [ 0 16  8 32]] 


A/B:
 [[       inf 1.33333333 0.57142857 1.        ]
 [0.75       6.         1.         1.25      ]
 [0.         4.         0.5        2.        ]] 


A*x:
 [[-0.7160173  -3.83288164 -1.04720252  2.80025382]
 [-2.14805189 -2.87466123 -2.35620566  1.75015864]
 [-0.         -3.83288164 -0.52360126  2.80025382]] 


A.T:
 [[2 6 0]
 [8 6 8]
 [4 9 2]
 [8 5 8]] 


x.T:
 [-0.35800865 -0.4791102  -0.26180063  0.35003173] 




/Users/matthew.mitchell/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in true_divide
  """


### 1. Generating Test Data
Generate two matrices of random data, A and B.  
Make matrix A a 3x4 matrix, and make B 4x4 matrix. Print both.

Calculate and print the following:
* $A^T$
* $B^T$
* AB
* $AB^T$
* $BA^T$

In [35]:
A = np.array([np.random.randint(0,10) for i in range(12)]).reshape((3,4))
B = np.array([np.random.randint(0,10) for i in range(16)]).reshape((4,4))

In [39]:
print('A :', A)
print('B :', B)

A : [[1 4 1 2]
 [0 2 8 6]
 [5 5 7 1]]
B : [[0 8 7 5]
 [3 5 7 2]
 [7 2 6 0]
 [6 5 8 2]]


In [43]:
B.transpose()

array([[0, 3, 7, 6],
       [8, 5, 2, 5],
       [7, 7, 6, 8],
       [5, 2, 0, 2]])

In [44]:
print('AB:', np.matmul(A,B))
print('AB^T', np.matmul(A,B.transpose()))
print('BA^T', np.matmul(B, A.transpose()))

AB: [[ 31  40  57  17]
 [ 98  56 110  16]
 [ 70  84 120  37]]
AB^T [[ 49  34  21  38]
 [102  78  52  86]
 [ 94  91  87 113]]
BA^T [[ 49 102  94]
 [ 34  78  91]
 [ 21  52  87]
 [ 38  86 113]]


#### 2. Describe what happens when you take the transpose of a matrix.

In [ ]:
#Describe the transpose of a matrix here.

### Systems of Equations
If you recall from your earlier life as a algebra student:

$2x +10 = 18$ has a unique solution; one variable, one equation, one solution

Similarly, two variables with two equations has one solution*   
$x+y=4$  
$2x+2y=10$

However, if we allow 2 variables with only 1 equation, we can have infinite solutions.
$x+y=4$

*(An inconsistent system will have no solution and a system where the second equation is a multiple of the first will have infinite solutions)

### 3. Representing Data as Matrices

#### A. Write a Matrix to represent this system:   
$x+y=4$  
$2x+2y=10$

In [ ]:
#Your matrix goes here

#### B. Multiply your matrix by 3. What is the resulting system of equations? 

In [ ]:
#Multiplying Matrix Here

In [ ]:
#Write the resulting system here

#### C. Solve both your original Matrix and the new Matrix that was the orginal, multiplied by 3. What do you notice?

### The Identity Matrix
The identity Matrix has ones running along the diagonal, and zeros everywhere else.
You can create an identity matrix of any given size by calling the built in numpy method:
numpy.identity(n) where n is the dimension of the desired matrix.

In [52]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 4. Multiply a matrix by the identity matrix. What do you notice? Explain why this happens.

In [ ]:
#Multiply a matrix by the identity matrix here.

In [ ]:
#Write your observations and explanation here.