# Representing Data as Matrices

![](./images/Matrix.svg.png)

### Numpy and Matrices
The numpy package will provide you a great toolbox of optimized mathematical operations including the numpy array, the most convenient way to store vector and matrix data for computation. Here, we'll look at some basic operations in numpy.

In [1]:
import numpy as np

In [3]:
A = np.array([np.random.randint(0,10) for i in range(12)]).reshape((3,4)) #Create a 3x4 matrix with random integers 0-9
B = np.array([np.random.randint(0,10) for i in range(12)]).reshape((3,4)) #Create a 3x4 matrix with random integers 0-9

x = np.random.randn(4) #An array of 4 samples from the standard normal distribution
y = np.random.randn(5) #An array of 5 samples from the standard normal distribution

print('A: {}'.format(A))
print('\n')
print('B: {}'.format(B))

print('\n\n')
print('x: {}'.format(x))
print('\n\n')
print('y: {}'.format(y))

A: [[8 1 5 3]
 [8 6 0 5]
 [4 6 6 2]]


B: [[8 8 0 8]
 [0 3 3 5]
 [8 9 9 3]]



x: [ 0.33200067  2.21259906 -1.35460712 -1.23272899]



y: [-0.21388341 -0.18904851  0.50919717 -0.66742028  0.45703783]


In [4]:
print('A+B:\n', A+B, '\n\n') # matrix addition
print('A-B:\n', A-B, '\n\n') # matrix subtraction
print('Be careful! This is not standard matrix multiplication!')
print('A*B:\n', A*B, '\n\n') # ELEMENTWISE multiplication
print('A/B:\n', A/B, '\n\n') # ELEMENTWISE division


print('A*x:\n', A*x, '\n\n') # multiply columns by x
print('A.T:\n', A.T, '\n\n') # transpose (just changes row/column ordering)
print('x.T:\n', x.T, '\n\n') # does nothing (can't transpose 1D array)

A+B:
 [[16  9  5 11]
 [ 8  9  3 10]
 [12 15 15  5]] 


A-B:
 [[ 0 -7  5 -5]
 [ 8  3 -3  0]
 [-4 -3 -3 -1]] 


Be careful! This is not standard matrix multiplication!
A*B:
 [[64  8  0 24]
 [ 0 18  0 25]
 [32 54 54  6]] 


A/B:
 [[1.         0.125             inf 0.375     ]
 [       inf 2.         0.         1.        ]
 [0.5        0.66666667 0.66666667 0.66666667]] 


A*x:
 [[ 2.65600539  2.21259906 -6.77303562 -3.69818698]
 [ 2.65600539 13.27559436 -0.         -6.16364497]
 [ 1.3280027  13.27559436 -8.12764274 -2.46545799]] 


A.T:
 [[8 8 4]
 [1 6 6]
 [5 0 6]
 [3 5 2]] 


x.T:
 [ 0.33200067  2.21259906 -1.35460712 -1.23272899] 




/Users/SamLiebman/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in true_divide
  """


### 1. Generating Test Data
Generate two matrices of random data, A and B.  
Make matrix A a 3x4 matrix, and make B 4x4 matrix. Print both.

Calculate and print the following:
* $A^T$
* $B^T$
* AB
* $AB^T$
* $BA^T$

In [8]:
A = np.array([np.random.randint(0,10) for i in range(12)]).reshape(3,4) #Your code goes here
B = np.array([np.random.randint(0,10) for i in range(16)]).reshape(4,4) #Your code goes here
print('A :', A)
print('B :', B)

A : [[1 7 5 5]
 [7 3 1 5]
 [7 1 9 1]]
B : [[4 5 7 6]
 [6 7 5 9]
 [3 2 1 8]
 [1 8 2 1]]


In [9]:
transpose_of_b = B.T#Your answer goes here
print('Transpose of B: {}'.format(transpose_of_b))

Transpose of B: [[4 6 3 1]
 [5 7 2 8]
 [7 5 1 2]
 [6 9 8 1]]


In [17]:
print('AB:', np.matmul(A,B) ) #Your code goes here
print('AB^T:',np.matmul(A,B.T)) #Your code goes here
print('BA^T:',np.matmul(B,A.T)) #Your code goes here

AB: [[ 66 104  57 114]
 [ 54  98  75  82]
 [ 62  68  65 124]]
AB^T: [[104 125  62  72]
 [ 80 113  68  38]
 [102 103  40  34]]
BA^T: [[104  80 102]
 [125 113 103]
 [ 62  68  40]
 [ 72  38  34]]


#### 2. Describe what happens when you take the transpose of a matrix.

Describe the transpose of a matrix here. Orientation is swapped. Rows become columns and columns become rows

### Systems of Equations
If you recall from your earlier life as a algebra student:

$2x +10 = 18$ has a unique solution; one variable, one equation, one solution

Similarly, two variables with two equations has one solution*   
$x+y=4$  
$2x+2y=10$

However, if we allow 2 variables with only 1 equation, we can have infinite solutions.
$x+y=4$

*(An inconsistent system will have no solution and a system where the second equation is a multiple of the first will have infinite solutions)

### 3. Representing Data as Matrices

#### A. Write a Matrix to represent this system:   
$x+y=4$  
$2x+2y=10$

In [22]:
#Your matrix goes here
A = np.array([[1,1,4],[2,2,10]])
A

array([[ 1,  1,  4],
       [ 2,  2, 10]])

#### B. Multiply your matrix by 3. What is the resulting system of equations? 

In [24]:
A*3   #Multiplying Matrix Here

array([[ 3,  3, 12],
       [ 6,  6, 30]])

## Write the resulting system here  
$3x+3y=12$  
$6x+6y=30$

### The Identity Matrix
The identity Matrix has ones running along the diagonal, and zeros everywhere else.
You can create an identity matrix of any given size by calling the built in numpy method:
numpy.identity(n) where n is the dimension of the desired matrix.

In [27]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 4. Multiply a matrix by the identity matrix. What do you notice? Explain why this happens.

In [38]:
#Multiply a matrix by the identity matrix here.
np.matmul(np.identity(2),A)

array([[ 1.,  1.,  4.],
       [ 2.,  2., 10.]])

In [39]:
A

array([[ 1,  1,  4],
       [ 2,  2, 10]])

#Write your observations and explanation here.

In [ ]:
the value of the matrix doesnt change