![](./images/Matrix.svg.png)

### Numpy and Matrices
The numpy package will provide you a great toolbox of optimized mathematical operations including the numpy array, the most convenient way to store vector and matrix data for computation. Here, we'll look at some basic operations in numpy.

In [1]:
import numpy as np

In [46]:
A = np.array([np.random.randint(0,10) for i in range(12)]).reshape((3,4)) #Create a 3x4 matrix with random integers 0-9
B = np.array([np.random.randint(0,10) for i in range(12)]).reshape((3,4)) #Create a 3x4 matrix with random integers 0-9

x = np.random.randn(4) #An array of 4 samples from the standard normal distribution
y = np.random.randn(5) #An array of 5 samples from the standard normal distribution

print('A: {}'.format(A))
print('\n')
print('B: {}'.format(B))

print('\n\n')
print('x: {}'.format(x))
print('\n\n')
print('y: {}'.format(y))

A: [[2 8 4 8]
 [6 6 9 5]
 [0 8 2 8]]


B: [[0 6 7 8]
 [8 1 9 4]
 [5 2 4 4]]



x: [-0.35800865 -0.4791102  -0.26180063  0.35003173]



y: [-0.29653411 -0.66575779 -0.46246297  0.2078026   2.11497751]


In [48]:
print('A+B:\n', A+B, '\n\n') # matrix addition
print('A-B:\n', A-B, '\n\n') # matrix subtraction
print('Be careful! This is not standarad matrix multiplication!')
print('A*B:\n', A*B, '\n\n') # ELEMENTWISE multiplication
print('A/B:\n', A/B, '\n\n') # ELEMENTWISE division


print('A*x:\n', A*x, '\n\n') # multiply columns by x
print('A.T:\n', A.T, '\n\n') # transpose (just changes row/column ordering)
print('x.T:\n', x.T, '\n\n') # does nothing (can't transpose 1D array)

A+B:
 [[ 2 14 11 16]
 [14  7 18  9]
 [ 5 10  6 12]] 


A-B:
 [[ 2  2 -3  0]
 [-2  5  0  1]
 [-5  6 -2  4]] 


Be careful! This is not standarad matrix multiplication!
A*B:
 [[ 0 48 28 64]
 [48  6 81 20]
 [ 0 16  8 32]] 


A/B:
 [[       inf 1.33333333 0.57142857 1.        ]
 [0.75       6.         1.         1.25      ]
 [0.         4.         0.5        2.        ]] 


A*x:
 [[-0.7160173  -3.83288164 -1.04720252  2.80025382]
 [-2.14805189 -2.87466123 -2.35620566  1.75015864]
 [-0.         -3.83288164 -0.52360126  2.80025382]] 


A.T:
 [[2 6 0]
 [8 6 8]
 [4 9 2]
 [8 5 8]] 


x.T:
 [-0.35800865 -0.4791102  -0.26180063  0.35003173] 




/Users/matthew.mitchell/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in true_divide
  """


### 1. Generating Test Data
Generate two matrices of random data, A and B.  
Make matrix A a 3x4 matrix, and make B 4x4 matrix. Print both.

Calculate and print the following:
* $A^T$
* $B^T$
* AB
* $AB^T$
* $BA^T$

In [3]:
A = np.array([np.random.randint(0,10) for i in range(12)]).reshape((3,4)) #Your code goes here
B = np.array([np.random.randint(0,10) for i in range(16)]).reshape((4,4)) #Your code goes here
print('A :', A)
print('B :', B)

A : [[2 7 3 7]
 [0 5 4 7]
 [4 0 5 8]]
B : [[0 3 5 2]
 [3 0 4 5]
 [7 5 6 1]
 [6 2 9 2]]


In [4]:
transpose_of_b = B.transpose() #Your answer goes here
print('Transpose of B: {}'.format(transpose_of_b))

Transpose of B: [[0 3 7 6]
 [3 0 5 2]
 [5 4 6 9]
 [2 5 1 2]]


In [5]:
print('AB:', np.matmul(A,B) #Your code goes here)
print('AB^T', np.matmul(A,B.transpose()) #Your code goes here)
print('BA^T', np.matmul(B, A.transpose()) #Your code goes here)

AB: [[ 84  35 119  56]
 [ 85  34 107  43]
 [ 83  53 122  29]]
AB^T [[50 53 74 67]
 [49 51 56 60]
 [41 72 66 85]]
BA^T [[50 49 41]
 [53 51 72]
 [74 56 66]
 [67 60 85]]


#### 2. Describe what happens when you take the transpose of a matrix.

Describe the transpose of a matrix here.
The orientation of the matrix is swapped; rows for columns and columns for rows.

### Systems of Equations
If you recall from your earlier life as a algebra student:

$2x +10 = 18$ has a unique solution; one variable, one equation, one solution

Similarly, two variables with two equations has one solution*   
$x+y=4$  
$2x+2y=10$

However, if we allow 2 variables with only 1 equation, we can have infinite solutions.
$x+y=4$

*(An inconsistent system will have no solution and a system where the second equation is a multiple of the first will have infinite solutions)

### 3. Representing Data as Matrices

#### A. Write a Matrix to represent this system:   
$x+y=4$  
$2x+2y=10$

In [9]:
#Your matrix goes here
A = np.array([[1,1,4],
     [2,2,10]
    ])
A

array([[ 1,  1,  4],
       [ 2,  2, 10]])

#### B. Multiply your matrix by 3. What is the resulting system of equations? 

In [10]:
#Multiplying Matrix Here
3*A

array([[ 3,  3, 12],
       [ 6,  6, 30]])

## Write the resulting system here  
$3x+3y=12$  
$6x+6y=30$

### The Identity Matrix
The identity Matrix has ones running along the diagonal, and zeros everywhere else.
You can create an identity matrix of any given size by calling the built in numpy method:
numpy.identity(n) where n is the dimension of the desired matrix.

In [52]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 4. Multiply a matrix by the identity matrix. What do you notice? Explain why this happens.

In [12]:
#Multiply a matrix by the identity matrix here.
print(A)
print(np.matmul(A, np.identity(3)))

[[ 1  1  4]
 [ 2  2 10]]
[[ 1.  1.  4.]
 [ 2.  2. 10.]]


#Write your observations and explanation here.
Multiplying by the identity matrix does not change the value of a matrix.